CREATE TABLE IF NOT EXISTS athlete (id TEXT PRIMARY KEY CHECK (id = 'athlete'), data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS activities (id TEXT PRIMARY KEY, date TEXT NOT NULL, confirmed INTEGER NOT NULL DEFAULT 0, source TEXT NOT NULL, data TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS activity_date ON activities(date);
CREATE TABLE IF NOT EXISTS plan_sessions (id TEXT PRIMARY KEY, date TEXT NOT NULL, status TEXT NOT NULL, data TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS plan_date ON plan_sessions(date);
CREATE TABLE IF NOT EXISTS coach_notes (id TEXT PRIMARY KEY, created_at TEXT NOT NULL, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, sequence INTEGER NOT NULL UNIQUE, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS operations (id TEXT PRIMARY KEY, input TEXT NOT NULL, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS turns (id TEXT PRIMARY KEY, text TEXT NOT NULL, status TEXT NOT NULL, response_id TEXT, updated_at TEXT NOT NULL);
